corner case bug in submit_genpipes

diff --git a/utils/submit_genpipes b/utils/submit_genpipes
--- a/utils/submit_genpipes
+++ b/utils/submit_genpipes
@@ -9,7 +9,6 @@ export SUBMIT_RETCODE=1
 export RETRY=10
 type squeue > /dev/null 2>&1 || SCHEDULER=pbs
 
-
 usage (){
 
 echo
@@ -24,8 +23,6 @@ echo "   -S <SCHEDULER>          Scheduler running on the cluster (slurm or pbs)
 echo "   -l <N>                  Will retry N time to resubmit a chunk if error occurs default=$RETRY"
 
 }
-
-
 
 get_n_jobs () {
   if [[ ${SCHEDULER} ==  'slurm' ]]; then
@@ -52,7 +49,7 @@ cancel_jobs () {
 cancel_trap () {
     cancel_jobs "$@" 2>/dev/null
     rm -rf $chunk_folder/.lockdir
-    exit 0
+    exit 1
 }
 
 submit () {
@@ -82,6 +79,7 @@ submit () {
     echo "could not complete submit after $RETRY retry"
     echo "Error log in ${job_script%.sh}.err:"
     cat "${job_script%.sh}.err"
+    return 1
   fi
 }
 
@@ -130,8 +128,6 @@ if [ $# -lt 1 ]; then
 fi
 chunk_folder=$(realpath "$1")
 
-
-
 if [ ! -d  ${chunk_folder} ]; then
   echo ${chunk_folder} does not exist
   exit 1
@@ -139,8 +135,6 @@ fi
 # sourcing to get the value of GENPIPES_CHUNK_SIZE
 source ${chunk_folder}/header.sh
 set +e
-
-
 
 mkdir ${chunk_folder}/.lockdir 2>/dev/null
 ret_code=$?
@@ -153,8 +147,6 @@ else
   trap "rm -rf $chunk_folder/.lockdir" EXIT
 fi
 
-
-
 all_sh=($(ls ${chunk_folder}/chunk*sh|sort -V))
 all_done=($chunk_folder/chunk*done)
 
@@ -164,18 +156,21 @@ for sh_script in "${all_sh[@]}"; do
     while true ; do
       curent_n_jobs=$(get_n_jobs)
       if [[ $((MAX_QUEUE-curent_n_jobs)) -gt $GENPIPES_CHUNK_SIZE ]]; then
-       submit ${sh_script}
-       touch ${done_script}
-       trap "rm -rf $chunk_folder/.lockdir" EXIT
-       break
+        submit ${sh_script}
+        ret_code=$?
+        trap "rm -rf $chunk_folder/.lockdir" EXIT
+        if [[ $ret_code -ne 0 ]]; then
+          # one of the chunk has failed, stop the process here
+          exit $ret_code
+        fi
+        touch ${done_script}
+        break
       else
-        echo too many jobs, sleeping for $SLEEP_TIME sec
-        sleep $SLEEP_TIME
+          echo too many jobs, sleeping for $SLEEP_TIME sec
+          sleep $SLEEP_TIME
       fi
     done
-
   fi
-
 done
 
 if [[ ${SUBMIT_RETCODE} -eq 0 ]]; then
