Remove debugging & checking version format in Action itself

diff --git a/.github/workflows/Update-Version-and-create-Realeases-PR.yml b/.github/workflows/Update-Version-and-create-Realeases-PR.yml
--- a/.github/workflows/Update-Version-and-create-Realeases-PR.yml
+++ b/.github/workflows/Update-Version-and-create-Realeases-PR.yml
@@ -7,7 +7,6 @@ on:
         description: 'Version name'
         required: true
         type: string
-        pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
 
 jobs:
   version:
@@ -22,6 +21,12 @@ jobs:
       id-token: write
 
     steps:
+      - name: Validate version format
+        run: |
+          if [[ ! "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version format. Must be in the format X.Y.Z"
+            exit 1
+          fi
       - name: Checkout code
         uses: actions/checkout@v4
         with:
@@ -71,9 +76,8 @@ jobs:
           genpipes -s tcsh > resources/autocomplete/genpipes.tcsh
       - name: Publish package to TestPyPI
         run: |
-          $(pdm venv activate)
           pdm build
-          pdm publish --repository testpypi --username __token__ --password ${{ secrets.TESTPYPI_API_TOKEN }} --verbose
+          pdm publish --repository testpypi --username __token__ --password ${{ secrets.TESTPYPI_API_TOKEN }}
       - name: Create pull request
         id: create_pr
         uses: peter-evans/create-pull-request@v7
